Revert "bus: change cancellation approach"
This caused lots of Cockpit tests to fail with

```
Exception ignored on calling ctypes callback function: <function Slot.__init__.<locals>.handler at 0x7f8e5fa18f40>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 280, in handler
    return 1 if callback(BusMessage.ref(message)) else 0
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/systemd_ctypes/bus.py", line 298, in done
    future.set_result(message)
asyncio.exceptions.InvalidStateError: invalid state
```

This reverts commit 389c90b82996d1b2872e07caca9b7931b5d552e9.