libsystemd: Fix mypy error about ctypes.Structure _fields assignment
> src/systemd_ctypes/libsystemd.py:80: error: Cannot override class variable (previously declared on base class "Structure") with instance variable  [misc]

This is the official way how to do that [1], so the code is correct.
However, the type is wrong, the top-level is a tuple. Drop the type
annotation completely, like in `sd_bus_error`, so that it is inherited
from the parent class.

[1] https://docs.python.org/3/library/ctypes.html